### ISSUE TITLE
httpget broken by guzzle update

### ISSUE THREAD

**Issue by telenieko** [phingofficial/phing#1385]
Hi,

I have a simple `httget` task that is now failing, rolling back #1357 fixes the issue, so it might be related.
I tested on the current master, with only that change.

The task:
```xml
                <httpget url="${packageUrl}"
                         dir="${packageRepository}" 
                         filename="${packageFileName}" />
```

The error:
```
BUILD FAILED
Undefined class constant 'MAJOR_VERSION'
#0 /Users/marc/Projects/phing/vendor/guzzlehttp/guzzle/src/functions.php(61): GuzzleHttp\Utils::defaultUserAgent()
#1 /Users/marc/Projects/espocrm/phing-files/vendor/guzzlehttp/guzzle/src/Client.php(278): GuzzleHttp\default_user_agent()
#2 /Users/marc/Projects/espocrm/phing-files/vendor/guzzlehttp/guzzle/src/Client.php(76): GuzzleHttp\Client->configureDefaults(Array)
#3 /Users/marc/Projects/phing/classes/phing/tasks/ext/HttpTask.php(162): GuzzleHttp\Client->__construct(Array)
#4 /Users/marc/Projects/phing/classes/phing/tasks/ext/HttpGetTask.php(87): HttpTask->request(Array)
#5 /Users/marc/Projects/phing/classes/phing/tasks/ext/HttpTask.php(188): HttpGetTask->request()
#6 /Users/marc/Projects/phing/classes/phing/UnknownElement.php(112): HttpTask->main()
#7 [internal function]: UnknownElement->main()
#8 /Users/marc/Projects/phing/classes/phing/dispatch/DispatchUtils.php(84): ReflectionMethod->invoke(Object(UnknownElement))
#9 /Users/marc/Projects/phing/classes/phing/Task.php(186): DispatchUtils::main(Object(UnknownElement))
#10 /Users/marc/Projects/phing/classes/phing/tasks/system/SequentialTask.php(56): Task->perform()
#11 /Users/marc/Projects/phing/classes/phing/tasks/system/IfTask.php(166): SequentialTask->main()
#12 [internal function]: IfTask->main()
#13 /Users/marc/Projects/phing/classes/phing/dispatch/DispatchUtils.php(84): ReflectionMethod->invoke(Object(IfTask))
#14 /Users/marc/Projects/phing/classes/phing/TaskAdapter.php(68): DispatchUtils::main(Object(IfTask))
#15 /Users/marc/Projects/phing/classes/phing/UnknownElement.php(112): TaskAdapter->main()
#16 [internal function]: UnknownElement->main()
#17 /Users/marc/Projects/phing/classes/phing/dispatch/DispatchUtils.php(84): ReflectionMethod->invoke(Object(UnknownElement))
#18 /Users/marc/Projects/phing/classes/phing/Task.php(186): DispatchUtils::main(Object(UnknownElement))
#19 /Users/marc/Projects/phing/classes/phing/Target.php(379): Task->perform()
#20 /Users/marc/Projects/phing/classes/phing/Target.php(409): Target->main()
#21 /Users/marc/Projects/phing/classes/phing/Project.php(784): Target->performTasks()
#22 /Users/marc/Projects/phing/classes/phing/Project.php(754): Project->executeTarget('ecDownloadCRM')
#23 /Users/marc/Projects/phing/classes/phing/Phing.php(750): Project->executeTargets(Array)
#24 /Users/marc/Projects/phing/classes/phing/Phing.php(220): Phing->runBuild()
#25 /Users/marc/Projects/phing/classes/phing/Phing.php(368): Phing::start(Array, NULL)
#26 /Users/marc/Projects/phing/bin/phing.php(60): Phing::fire(Array)
#27 /Users/marc/Projects/phing/bin/phing(13): require_once('/Users/marc/Pro...')
#28 {main}
```

**Comment by siad007** [comment]
@telenieko this is caused by https://github.com/guzzle/guzzle/issues/2744 - I will have a look how we could solve it.

**Comment by siad007** [comment]
@telenieko thanks for the report - it was fixed with https://github.com/phingofficial/phing/pull/1386/commits/7a90a1fa893c932bafe4e333f08be4c795fb2296
