### ISSUE TITLE
Parallel Task: Call to a member function push() on null in ... Manager.php:237

### ISSUE THREAD

**Issue by Haehnchen** [phingofficial/phing#706]
Looks there is an issue in parallel task `isset`

```
if (isset($worker->pipe)) {
```

https://github.com/phingofficial/phing/blob/master/classes/phing/contrib/DocBlox/Parallel/Manager.php#L237

```
PHP Fatal error:  Uncaught Error: Call to a member function push() on null in ./vendor/phing/phing/classes/phing/contrib/DocBlox/Parallel/Manager.php:237
Stack trace:
#0 ./vendor/phing/phing/classes/phing/contrib/DocBlox/Parallel/Manager.php(190): DocBlox_Parallel_Manager->stopExecution(Array)
#1 ./vendor/phing/phing/classes/phing/tasks/ext/ParallelTask.php(81): DocBlox_Parallel_Manager->execute()
#2 ./vendor/phing/phing/classes/phing/UnknownElement.php(100): ParallelTask->main()
#3 ./vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#4 ./vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#5 ./vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#6 ./vendor/phing/phing/classes/phing/Project.php(898): Targ in ./vendor/phing/phing/classes/phing/contrib/DocBlox/Parallel/Manager.php on line 237
```

**Comment by mrook** [comment]
Closed by #707.
