### ISSUE TITLE
ansible在远程机器上启动docker容器抱下面这个错，大神麻烦指导下 0=0🙏

### ISSUE THREAD

**Issue by liyueliyue** [phingofficial/phing#948]
TASK [docker : install docker-py] ************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [docker : service on] *******************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [docker : Create docker_home directory] *************************************************************************************************************************************
ok: [127.0.0.1]

TASK [docker-jenkins : Create /docker/docker_jenkins directory] ******************************************************************************************************************
ok: [127.0.0.1]

TASK [docker-jenkins : Copy files to server] *************************************************************************************************************************************
ok: [127.0.0.1]

TASK [docker-jenkins : Copy templates to server] *********************************************************************************************************************************
ok: [127.0.0.1] => (item=Dockerfile)
ok: [127.0.0.1] => (item=security.groovy)

TASK [docker-jenkins : Build docker-jenkins image] *******************************************************************************************************************************
ok: [127.0.0.1]

TASK [docker-jenkins : Create docker-jenkins container] **************************************************************************************************************************
fatal: [127.0.0.1]: FAILED!

=====》
{
"changed": false,
"module_stderr": "Shared connection to 127.0.0.1 closed.
",
"module_stdout": "Traceback (most recent call last):
File "/tmp/ansible_PjsG9O/ansible_module_docker_container.py", line 2081, in 
main()
File "/tmp/ansible_PjsG9O/ansible_module_docker_container.py", line 2076, in main
cm = ContainerManager(client)
File "/tmp/ansible_PjsG9O/ansible_module_docker_container.py", line 1703, in init
self.present(state)
File "/tmp/ansible_PjsG9O/ansible_module_docker_container.py", line 1723, in present
new_container = self.container_create(self.parameters.image, self.parameters.create_parameters)
File "/tmp/ansible_PjsG9O/ansible_module_docker_container.py", line 825, in create_parameters
host_config=self._host_config(),
File "/tmp/ansible_PjsG9O/ansible_module_docker_container.py", line 931, in _host_config
return self.client.create_host_config(**params)
File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 157, in create_host_config
return utils.create_host_config(*args, **kwargs)
TypeError: create_host_config() got an unexpected keyword argument 'init'
",
"msg": "MODULE FAILURE",
"rc": 1
}

**Comment by mrook** [comment]
I'm not entirely sure what this log dump has to do with Phing. Can you clarify @liyueliyue ?
