### ISSUE TITLE
phing.tasks.system.ExecTask doesn't support the 'env' creator/adder.'

### ISSUE THREAD

**Issue by GrzegorzDrozd** [phingofficial/phing#971]
Hi,

According to the documentation I should be able to set env variables for exec task: https://www.phing.info/phing/guide/en/output/chunkhtml/ExecTask.html
But when I do that I am getting this error:
```
exception 'BuildException' with message '/data/jenkins/workspace/<PROJECT>/build.xml:103:41: phing.tasks.system.ExecTask doesn't support the 'env' creator/adder.' in phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/IntrospectionHelper.php:517
Stack trace:
#0 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/UnknownElement.php(144): IntrospectionHelper->createElement(Object(Project), Object(ExecTask), 'env')
#1 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/UnknownElement.php(81): UnknownElement->handleChildren(Object(ExecTask), Object(RuntimeConfigurable))
#2 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Task.php(282): UnknownElement->maybeConfigure()
#3 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Target.php(336): Task->perform()
#4 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Target.php(366): Target->main()
#5 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Project.php(898): Target->performTasks()
#6 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Project.php(868): Project->executeTarget('test')
#7 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Phing.php(723): Project->executeTargets(Array)
#8 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Phing.php(200): Phing->runBuild()
#9 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#10 phar:///data/jenkins/workspace/<PROJECT>/phing-latest.phar/bin/phing.php(58): Phing::fire(Array)
#11 /data/jenkins/workspace/<PROJECT>/phing-latest.phar(6): include('phar:///data/je...')
#12 {main}
```

My build file looks like this:
```
        <echo message="Running acceptance tests on source code" />
        <exec executable="php" checkreturn="true" dir="${application.startdir}" >
            <arg line="-dmemory_limit=3G" />
            <arg line="-f '${application.startdir}/vendor/codeception/codeception/codecept' -- " />
            <arg line="-c codeception.yml" />
            <arg line="run tests/acceptance" />
            <arg line="--env staging" />
            <arg line="--xml" />
            <env key="BRANCH" value="${branchNameLowerCase}" />
        </exec>
```

Phing version:
```
php -f phing-latest.phar -- -v
Phing 2.16.1
```

**Comment by mrook** [comment]
Hi @GrzegorzDrozd, the `env` tag is not available in the 2.x series, only in 3.x (an alpha version has been released).

**Comment by GrzegorzDrozd** [comment]
Does 3.x version works on php 5.6.x?
Maybe a tag or some comment in documentation with that information?

**Comment by mrook** [comment]
No, 3.x is targeted for PHP 7+. I'll add a note to the phing.info site.

**Comment by mrook** [comment]
Made a note in https://github.com/phingofficial/phingofficial.github.io/commit/c994c616387ad773cbd946703bc65331a2fea9d5. Thanks!
